logging:
  file:
    name: d:/tmp/logs/Hamburger.log
  level:
    space:
      bumtiger: DEBUG

credential:
  ccNumber: 4263982640269299
  ccExpiration: 12/26

spring:
  profiles:
    active:
    - prod
    include: prod_sec
    
  application:
    name: burger_service

---
logging:
  level:
    space:
      bumtiger: WARN
    root: INFO
    org:
      springframework:
        security: DEBUG  
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/hamburger
    username: burger
    password: 4899

server:
  port: 8443
  ssl:
    key-store: d:/home/data/keystore.jks
    key-store-password: letmein
    key-password: letmein
