# h2 database web으로 확인
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hamburger # In-Memory mode 
    username: root
    password: 1234
    driverClassName: org.h2.Driver # spring - h2 연결

  sql:
    init:
      schema-locations: classpath:schema_h2.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
