logging:
  file:
    name: d:/tmp/logs/Hamburger.log
  level:
    space:
      bumtiger: DEBUG

credential:
  ccNumber: 4263982640269299
  ccExpiration: 12/26

spring:
  profiles:
    active: prod
    include: prod_sec
    
  application:
    name: burger_service

---
logging:
  level:
    space:
      bumtiger: WARN
    root: INFO
    org:
      springframework:
        security: DEBUG  
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/hamburger
    username: burger
    password: 4899

---
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:hamburger # In-Memory mode 
    username: root
    password: 1234
    driverClassName: org.h2.Driver # spring - h2 연결

  sql:
    init:
      schema-locations: classpath:schema_h2.sql
      data-locations:
      - classpath:data_h2.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
